# Generated by Django 5.1.6 on 2025-03-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
