# Generated by Django 5.1.7 on 2025-03-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_app', '0002_delete_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
